name: CI

on: [push]

jobs:
  sast_scan:
    name: RUN Sast_Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install Bandit
      run: pip install bandit

    - name: Run bandit
      run: bandit -r -ii -ll . -f json -o bandit-report-log.json

    - name: upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit logs
        path: bandit-report-log.json
  image_scan:
    name: Build Image and scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0
        with:
          docker_version: '20.10'

      - name: build image
        run: docker build -f Dockerfile -t myapp:latest .

      # - name: scout
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
      #     sh install-scout.sh

      #     echo ${{ secrets.DOCKER_PSWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin 
      #     docker scout quickview
      #     docker scout cves

      - name: docker scout
        uses: docker/scout-action@v1.5.0
        with:
          dockerhub-user: ${{secrets.REPO_USER}}
          dockkerhub-password: ${{secretts.DOCKER_PSWD}}
          command: quickview,cves
            
              
